name: MAIN

on:
  push:
    branches:
      - master
    schedule:
      - cron: '0 0 */7 * *'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Install chrome & web driver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver chromium-browser
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run
      run: |
        python main.py ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }}
